# Generated by Django 2.2.17 on 2023-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopLevelDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tld', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='topLevelDomain',
            field=models.ManyToManyField(to='countries.TopLevelDomain'),
        ),
    ]
